 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
128.61.82.46 - - [31/Aug/2015 02:54:30] "GET /ask HTTP/1.1" 200 -
128.61.82.46 - - [31/Aug/2015 02:54:36] "GET /ask HTTP/1.1" 200 -
128.61.82.46 - - [31/Aug/2015 02:54:37] "GET /ask HTTP/1.1" 200 -
128.61.82.46 - - [31/Aug/2015 02:54:38] "GET /ask HTTP/1.1" 200 -
128.61.82.46 - - [31/Aug/2015 02:54:51] "GET /askkjfdlk HTTP/1.1" 404 -
128.61.82.46 - - [31/Aug/2015 02:55:00] "GET / HTTP/1.1" 200 -
128.61.82.46 - - [31/Aug/2015 02:55:01] "GET /favicon.ico HTTP/1.1" 404 -
143.215.85.26 - - [31/Aug/2015 02:55:02] "GET / HTTP/1.1" 200 -
143.215.85.26 - - [31/Aug/2015 02:55:02] "GET /favicon.ico HTTP/1.1" 404 -
143.215.85.26 - - [31/Aug/2015 02:55:02] "GET /favicon.ico HTTP/1.1" 404 -
128.61.82.46 - - [31/Aug/2015 02:55:06] "GET /ask HTTP/1.1" 200 -
143.215.85.26 - - [31/Aug/2015 02:55:09] "GET /ask HTTP/1.1" 200 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
143.215.85.26 - - [31/Aug/2015 02:58:50] "GET /ask HTTP/1.1" 404 -
143.215.85.26 - - [31/Aug/2015 02:58:57] "GET /article/recnet/1 HTTP/1.1" 404 -
143.215.85.26 - - [31/Aug/2015 02:59:01] "GET /article/recent/1 HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "api.py", line 26, in <module>
    main()
  File "api.py", line 23, in main
    app.run(host='0.0.0.0', port=5000)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 618, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
143.215.85.26 - - [31/Aug/2015 02:59:55] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 02:59:55] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 02:59:55] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 02:59:56] "GET /article/recent/1 HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "api.py", line 26, in <module>
    main()
  File "api.py", line 23, in main
    app.run(host='0.0.0.0', port=5000)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 618, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
143.215.85.26 - - [31/Aug/2015 03:00:06] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 03:00:08] "GET / HTTP/1.1" 200 -
143.215.85.26 - - [31/Aug/2015 03:00:10] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 03:00:10] "GET /article/recent/1 HTTP/1.1" 500 -
143.215.85.26 - - [31/Aug/2015 03:00:11] "GET /article/recent/1 HTTP/1.1" 500 -
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "api.py", line 26, in <module>
    main()
  File "api.py", line 23, in main
    app.run(host='0.0.0.0', port=5000, debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 618, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
